/* Programme de mathématiques du cycle 4 (annexe 2) + attendus de fin d'année 5e/4e/3e.
   Généré à partir des PDF officiels. Format : [niveau, domaine, thème, type (o=objectif, a=automatisme, e=attendu), texte] */
const BO_DATA=[
["5e", "Nombres et calculs", "Opérations", "a", "Mobiliser les critères de divisibilité par 2, 5 et 10 vus en CM1 et CM2."],
["5e", "Nombres et calculs", "Opérations", "a", "Déterminer le quotient et le reste dans une division euclidienne, par exemple, savoir que 17 = 3 × 5 + 2."],
["5e", "Nombres et calculs", "Opérations", "a", "Utiliser les tables de multiplication pour factoriser des nombres entiers décomposables en produit de deux nombres différents de 1, par exemple, 21 = 3 × 7."],
["5e", "Nombres et calculs", "Opérations", "a", "Savoir calculer des produits en lien avec les tables : 0,6 × 7 ; 40 × 0,03."],
["5e", "Nombres et calculs", "Opérations", "a", "Multiplier et diviser par 10, 100, 1 000."],
["5e", "Nombres et calculs", "Opérations", "a", "Additionner et soustraire des décimaux, par exemple, 2,7 + 1,4 ; 3,4 – 0,8."],
["5e", "Nombres et calculs", "Opérations", "o", "Additionner, soustraire, multiplier et diviser pour résoudre des problèmes et contrôler la vraisemblance de son résultat."],
["5e", "Nombres et calculs", "Opérations", "o", "Connaitre le sens et les situations d’emploi de ces opérations."],
["5e", "Nombres et calculs", "Opérations", "o", "Diviser par un nombre décimal."],
["5e", "Nombres et calculs", "Opérations", "o", "Enchainer des opérations."],
["5e", "Nombres et calculs", "Opérations", "o", "Traduire un problème, une succession donnée d’opérations, un programme de calcul, en une seule expression, en faisant appel ou non à des parenthèses."],
["5e", "Nombres et calculs", "Opérations", "o", "Nommer un calcul, distinguer sommes et produits, termes et facteurs."],
["5e", "Nombres et calculs", "Opérations", "o", "Connaitre et utiliser les priorités opératoires."],
["5e", "Nombres et calculs", "Opérations", "o", "Connaitre et utiliser la distributivité simple sur des exemples numériques."],
["5e", "Nombres et calculs", "Opérations", "o", "Utiliser les notions de multiples et diviseurs."],
["5e", "Nombres et calculs", "Opérations", "o", "Connaitre les critères de divisibilité par 3 et par 9."],
["5e", "Nombres et calculs", "Opérations", "o", "Mobiliser un algorithme dans le cadre du calcul numérique."],
["5e", "Nombres et calculs", "Nombres relatifs", "a", "Additionner, soustraire, multiplier des nombres décimaux à une ou deux décimales."],
["5e", "Nombres et calculs", "Nombres relatifs", "a", "Savoir que pour compléter une addition à trou, on utilise une soustraction : 2 + ... = 7 se complète en calculant 7 – 2."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Définir les nombres relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Définir l’opposé et la valeur absolue d’un nombre."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Définir la notion de nombre positif, strictement positif, négatif, strictement négatif."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Utiliser les nombres relatifs pour représenter des grandeurs observables qui peuvent prendre des valeurs inférieures à zéro (température, temps, altitude, etc.), en particulier dans le cadre de la résolution de problèmes."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Lire l’abscisse d’un nombre relatif sur une droite graduée et placer un nombre relatif d’abscisse donnée."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Comparer et ranger dans l’ordre croissant et décroissant des nombres décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Additionner deux nombres décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Additionner plusieurs nombres décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Soustraire deux nombres décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Connaitre et justifier les situations dans lesquelles des parenthèses sont indispensables au sens des écritures."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Simplifier l’écriture de sommes comportant des parenthèses."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Enchainer additions et soustractions de décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres relatifs", "o", "Résoudre des problèmes mobilisant addition et soustraction de nombres décimaux relatifs."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Entretenir la connaissance et l’utilisation des tables de multiplication."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Entretenir l’écriture décimale des fractions simples comme ; ; ; ; ; ; ; ; ."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Faire vivre la notion de nombre quotient en complétant des multiplications à trou : 3 × … = 7 puis 3 × = …"],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Lire l’abscisse d’un point sur une droite graduée en tiers, en quarts, en moitiés, en dixièmes."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Reconnaitre des fractions égales : = ; = ."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Comparer deux fractions : et ; et ; et ; et ."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Écrire une fraction sous la forme d’une somme d’un nombre entier et d’une fraction inférieure à 1 : =3+ ."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Addition et soustraction de fractions simples : + ; 1 – ; – ;3+ ; + ."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Prendre une fraction simple d’un nombre : le de 18 ; le de 12."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Prendre 1 %, 10 % ou 50 % d’un nombre, en lien avec la proportionnalité."],
["5e", "Nombres et calculs", "Nombres rationnels", "a", "Écrire un même nombre sous de multiples formes, par exemple dire que 1,2 = = = 1 + = 120 % = etc."],
["5e", "Nombres et calculs", "Nombres rationnels", "o", "Comparer des fractions."],
["5e", "Nombres et calculs", "Nombres rationnels", "o", "Additionner et soustraire des fractions de dénominateurs quelconques."],
["5e", "Nombres et calculs", "Nombres rationnels", "o", "Résoudre des problèmes avec des additions et soustractions de fractions."],
["5e", "Nombres et calculs", "Puissances", "a", "Entretenir les tables de multiplications."],
["5e", "Nombres et calculs", "Puissances", "a", "Connaitre les unités d’aires et de volume."],
["5e", "Nombres et calculs", "Puissances", "o", "Découvrir la notion de puissance d’un nombre et sa notation dans le cas du carré et du cube."],
["5e", "Nombres et calculs", "Puissances", "o", "Connaitre les carrés des entiers de 0 à 12."],
["5e", "Nombres et calculs", "Puissances", "o", "Connaitre le cube de 10."],
["5e", "Nombres et calculs", "Puissances", "o", "Savoir écrire un nombre sous la forme d’une puissance 2 ou 3."],
["5e", "Nombres et calculs", "Puissances", "o", "Calculer la valeur numérique d’expressions contenant des puissances simples, additions, soustractions et produits."],
["5e", "Nombres et calculs", "Puissances", "o", "Calculer la valeur d’une expression littérale contenant une puissance simple."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Identifier des régularités et poursuivre une suite de motifs évolutive."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Trouver le nombre d’éléments pour une étape donnée dans une suite de motifs évolutive."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Identifier la structure d’un motif évolutif en repérant une régularité."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Nombre quotient."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Produire des formules (double, triple, carré, successeur, prédécesseur, aire, périmètre, etc.)."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Calculer la valeur d’une expression littérale par substitution."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Tester si une égalité entre expressions algébriques comportant une variable est vraie ou fausse."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Déterminer si une expression littérale est une somme ou un produit."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Exploiter les relations k(a + b) = ka + kb ou k(a – b) = ka – kb pour factoriser, ou développer une expression littérale."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Réduire une expression littérale de la forme a𝑥 + b, où a et b sont des nombres décimaux."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Démontrer une propriété générale par le calcul littéral."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Utiliser un contre-exemple pour démontrer qu’une assertion est fausse."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Formuler des conjectures en s’appuyant sur un langage algorithmique ou un tableur."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Donner à la lettre le statut d’inconnue."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Modéliser des problèmes relevant des opérations à trous par des équations du type a𝑥 = c ou 𝑥 + b = c ."],
["5e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Résoudre des équations du type a𝑥 = c ou 𝑥 + b = c par des méthodes arithmétiques s'appuyant sur les opérations inverses."],
["5e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Placer sur une demi-droite graduée un point dont l’abscisse est un nombre décimal."],
["5e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Repérer un nombre décimal sur une demi-droite graduée."],
["5e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "o", "Sur une droite graduée :\n- lire l’abscisse d’un point donné ;\n- placer un point d’abscisse donnée."],
["5e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "o", "Dans le plan muni d’un repère orthogonal :\n- lire les coordonnées d’un point donné ;\n- placer un point de coordonnées données."],
["5e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre des vues (de dessus, dessous…) d’empilements de cubes."],
["5e", "Espace et géométrie", "Représentation de l’espace", "a", "Dénombrer des cubes dans des empilements."],
["5e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre un cube, un pavé représenté en perspective cavalière."],
["5e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre un patron d’un cube."],
["5e", "Espace et géométrie", "Représentation de l’espace", "o", "Construire et mettre en relation différentes représentations en perspectives cavalières des solides suivants : pavé droit, cube, cylindre de révolution, prisme droit."],
["5e", "Espace et géométrie", "Représentation de l’espace", "o", "Savoir mettre en relation une représentation en perspective cavalière et un patron d’un pavé, d’un prisme droit ou d’un cylindre de révolution."],
["5e", "Espace et géométrie", "Représentation de l’espace", "o", "Calculer le volume du cube, du pavé droit, du prisme droit."],
["5e", "Espace et géométrie", "Représentation de l’espace", "o", "Connaitre et convertir des unités usuelles (volume et capacité)."],
["5e", "Espace et géométrie", "Représentation de l’espace", "o", "Calculer l’aire du disque, le volume du cylindre de révolution."],
["5e", "Espace et géométrie", "Transformations", "a", "Reconnaitre et construire le symétrique d’une figure par symétrie axiale, dont l’axe est vertical, horizontal, ou en diagonale sur quadrillage."],
["5e", "Espace et géométrie", "Transformations", "a", "Construire le symétrique, par rapport à un axe, d’un point, d’une figure, sur feuille blanche."],
["5e", "Espace et géométrie", "Transformations", "o", "Définir le demi-tour, ou symétrie centrale."],
["5e", "Espace et géométrie", "Transformations", "o", "Connaitre les propriétés du demi-tour."],
["5e", "Espace et géométrie", "Angles", "a", "Reconnaitre et citer sur une configuration géométrique des angles : angle plein, plat, nul, droit ; angles opposés par le sommet, adjacents, supplémentaires, aigus, obtus."],
["5e", "Espace et géométrie", "Angles", "a", "Savoir qu’un angle droit mesure 90°, qu’un angle plat mesure 180°."],
["5e", "Espace et géométrie", "Angles", "a", "Reconnaitre une bissectrice."],
["5e", "Espace et géométrie", "Angles", "a", "Connaitre les mesures des angles de l’équerre dont dispose l’élève (30° 60° 90° ou 45° 45° 90°)."],
["5e", "Espace et géométrie", "Angles", "o", "Caractériser le parallélisme par les angles : angles alternes internes, angles correspondants."],
["5e", "Espace et géométrie", "Triangles", "a", "Reconnaitre un triangle isocèle, équilatéral ou rectangle à partir d’un schéma codé."],
["5e", "Espace et géométrie", "Triangles", "a", "Connaitre la somme des angles d’un triangle, calculer le 3e angle d’un triangle connaissant les mesures des deux autres."],
["5e", "Espace et géométrie", "Triangles", "a", "Connaitre la notion de médiatrice, de cercle circonscrit."],
["5e", "Espace et géométrie", "Triangles", "o", "Connaitre la somme des angles d’un triangle et savoir la démontrer."],
["5e", "Espace et géométrie", "Triangles", "o", "Construire des triangles à partir de données partielles."],
["5e", "Espace et géométrie", "Triangles", "o", "Connaitre les propriétés des médiatrices et du cercle circonscrit dans le cas de triangles particuliers."],
["5e", "Espace et géométrie", "Triangles", "o", "Calculer l’aire d’un triangle."],
["5e", "Espace et géométrie", "Triangles", "o", "Définir et tracer les hauteurs dans un triangle."],
["5e", "Espace et géométrie", "Triangles", "o", "Savoir que les hauteurs d’un triangle sont concourantes."],
["5e", "Espace et géométrie", "Triangles", "o", "Définir et tracer les médianes dans un triangle."],
["5e", "Espace et géométrie", "Triangles", "o", "Démontrer qu’une médiane partage un triangle en deux triangles d’aires égales."],
["5e", "Espace et géométrie", "Triangles", "o", "Utiliser ces propriétés dans le cas de triangles particuliers."],
["5e", "Espace et géométrie", "Parallélogrammes", "a", "Reconnaitre en justifiant un quadrilatère, un parallélogramme, un rectangle, un losange, un carré, un trapèze, un pentagone, un hexagone dans des figures complexes."],
["5e", "Espace et géométrie", "Parallélogrammes", "a", "Exploiter le codage d’une figure pour identifier des parallélogrammes particuliers."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Définir le parallélogramme."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Construire des parallélogrammes."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Connaitre les propriétés caractéristiques des côtés opposés et des diagonales."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Utiliser une propriété caractéristique sur les diagonales ou les côtés pour les construire ou donner la nature du quadrilatère."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Définir les parallélogrammes particuliers (rectangle, losange, carré)."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Connaitre les propriétés caractéristiques."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Savoir calculer l’aire d’un parallélogramme et de figures complexes."],
["5e", "Espace et géométrie", "Parallélogrammes", "o", "Résoudre des problèmes faisant appel à des conversions d’unités de longueur et d’unités d’aires."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Recueillir et organiser des données."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Calculer des effectifs et des fréquences (exprimées sous forme décimale, fractionnaire ou de pourcentage)."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Lire et interpréter des informations présentées sous forme de tableaux, de diagrammes et de graphiques."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Représenter, sur papier ou à l’aide d’un tableur-grapheur, des données sous la forme d’un tableau, d’un diagramme (diagramme en barres, diagramme circulaire) ou d’un graphique cartésien."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Choisir une représentation adaptée à ce qu’il convient de mettre en avant."],
["5e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Calculer et interpréter la moyenne simple d’une série de données."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "a", "Positionner sur une échelle de probabilité les évènements du type :\n• évènement impossible ;\n• évènement certain ;\n• obtenir pile en lançant une pièce équilibrée ;\n• obtenir une valeur donnée en lançant un dé équilibré ;\n• obtenir une couleur d’une boule lors du tirage dans une urne ;\n• ne pas obtenir la bonne combinaison au loto ;\n• obtenir 10 fois de suite la valeur 1 en lançant un dé à six faces."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "a", "Donner la probabilité sous diverses formes (fraction, décimale, pourcentage) pour les cinq premiers évènements ci-dessus."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "a", "Lier l’expression « une chance sur quatre » (par exemple) et la probabilité ."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Aborder les questions relatives au hasard à partir de problèmes simples."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Utiliser le vocabulaire des probabilités dans des contextes concrets : expérience aléatoire, issue, évènement."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Attribuer des probabilités dans des cas simples (équiprobabilité)."],
["5e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Répéter matériellement une expérience aléatoire simple. Enregistrer les résultats observés dans un tableau d’effectifs et de fréquences."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Reconnaitre si une situation donnée entre dans le cadre de la proportionnalité ou non."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Dans des situations simples, mobiliser une procédure adaptée (propriété de linéarité pour la multiplication ou l’addition, retour à l’unité) pour résoudre un problème lié à la proportionnalité. Par exemple :\n• à partir d’une recette pour 4 personnes, on sait donner (ou verbaliser la procédure) les quantités lorsque l’on passe à 2, 8 ou 6 personnes ;\n• si l’on connait le prix d’un kilogramme de tomates, on sait comment calculer le prix de 3 kg ou de 4,3 kg de tomates ;\n• lors de l’élection des délégués de la classe, 4 élèves se présentent. Chaque élève a voté pour un seul candidat. Voici les résultats : Alexis         Chloé           Salma          Djibril        Total Calculer le pourcentage de voix de chaque candidat."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Utiliser des proportions, des pourcentages."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Calculer, appliquer des proportions, des pourcentages."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Identifier des situations de proportionnalité dans des contextes concrets (prix, recettes, distances, échelles)."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Utiliser un coefficient de proportionnalité dans des contextes concrets (prix unitaire, vitesse moyenne, échelle, etc.)."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Représenter une situation de proportionnalité par un tableau ou un graphique."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Reconnaitre une situation de proportionnalité à partir d’un tableau ou d’un graphique."],
["5e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Reconnaitre graphiquement qu’un nuage de points est ou n’est pas associé à une situation de proportionnalité entre données discrètes."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Introduire l’expression : « en fonction de » dans des contextes concrets ou mathématiques."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Produire un tableau de valeurs."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Lire et interpréter un tableau de valeurs."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Placer dans un repère orthogonal donné des points correspondant à un tableau de valeurs."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Lire et interpréter un graphique cartésien donné par une courbe ou un nuage de points."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Traduire la relation de dépendance entre deux grandeurs par un tableau de valeurs à partir d’une formule."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Produire une formule simple représentant la dépendance de deux grandeurs."],
["5e", "Proportionnalité, fonctions", "Fonctions", "o", "Caractériser graphiquement la proportionnalité."],
["5e", "La pensée informatique", "Algorithmique", "o", "Manipuler des instructions simples et les séquencer."],
["5e", "La pensée informatique", "Algorithmique", "o", "Identifier les entrées et sorties d’un programme."],
["5e", "La pensée informatique", "Algorithmique", "o", "Représenter des formules sous la forme d’une expression informatique dans un langage de programmation par blocs."],
["5e", "La pensée informatique", "Algorithmique", "o", "Calculer la valeur de formules à l’aide d’une suite d’instruction dans un langage de programmation par blocs."],
["5e", "La pensée informatique", "Algorithmique", "o", "Prévoir la valeur d’une expression informatique avant son exécution."],
["5e", "La pensée informatique", "Algorithmique", "o", "Analyser un programme simple donné et modifier ses paramètres."],
["5e", "La pensée informatique", "Algorithmique", "o", "Effectuer une boucle inconditionnelle simple permettant de répéter une séquence linéaire d’instructions un nombre précis de fois."],
["5e", "Attendus de fin d’année", "Nombres", "e", "Il utilise, dans le cas des nombres décimaux, les écritures décimales et fractionnaires et passe de l’une à l’autre, en particulier dans le cadre de la résolution de problèmes."],
["5e", "Attendus de fin d’année", "Nombres", "e", "Il relie fractions, proportions et pourcentages."],
["5e", "Attendus de fin d’année", "Nombres", "e", "Il décompose une fraction sous la forme d’une somme (ou d’une différence) d’un entier et d’une fraction."],
["5e", "Attendus de fin d’année", "Nombres", "e", "Il utilise la notion d’opposé."],
["5e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il reconnaît et produit des fractions égales."],
["5e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il compare, range, encadre des fractions dont les dénominateurs sont égaux ou multiples l’un de l’autre."],
["5e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il repère sur une droite graduée les nombres décimaux relatifs."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il traduit un enchaînement d’opérations à l’aide d’une expression avec des parenthèses."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il effectue mentalement, à la main ou l’aide d’une calculatrice un enchaînement d’opérations en respectant les priorités opératoires."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il additionne et soustrait des nombres décimaux relatifs."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il additionne ou soustrait des fractions dont les dénominateurs sont égaux ou multiples l’un de l’autre."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il contrôle la vraisemblance d’un résultat."],
["5e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il résout des problèmes faisant intervenir des nombres décimaux relatifs et des fractions."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il calcule le quotient et le reste dans une division euclidienne."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il détermine si un nombre entier est ou n’est pas multiple ou diviseur d’un autre nombre entier."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il détermine les nombres premiers inférieurs ou égaux à 30."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il utilise les critères de divisibilité (par 2, 3, 5, 9, 10)."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il décompose un nombre entier strictement positif en produit de facteurs premiers inférieurs à"],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il utilise la décomposition en facteurs premiers inférieurs à 30 pour produire des fractions égales (simplification ou mise au même dénominateur)."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il modélise et résout des problèmes faisant intervenir les notions de multiple, de diviseur, de quotient et de reste."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il utilise les notations 2a pour a × 2 ou 2 × a et ab pour a × b, a pour a × a et a pour a × a × a."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il utilise la distributivité simple pour réduire une expression littérale de la forme ax + bx où a et b sont des nombres décimaux."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il produit une expression littérale pour élaborer une formule ou traduire un programme de calcul."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il utilise une lettre pour traduire des propriétés générales."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il utilise une lettre pour démontrer une propriété générale."],
["5e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il substitue une valeur numérique à une lettre pour : - calculer la valeur d’une expression littérale ; - tester, à la main ou de façon instrumentée, si une égalité où figurent une ou deux indéterminées est vraie quand on leur attribue des valeurs numériques ; - contrôler son résultat."],
["5e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il recueille et organise des données."],
["5e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il lit et interprète des données brutes ou présentées sous forme de tableaux, de diagrammes et de graphiques."],
["5e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il représente, sur papier ou à l’aide d’un tableur-grapheur, des données sous la forme d’un tableau, d’un diagramme ou d’un graphique."],
["5e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il calcule des effectifs et des fréquences."],
["5e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il calcule et interprète la moyenne d’une série de données."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il place un événement sur une échelle de probabilités."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il calcule des probabilités dans des situations simples d’équiprobabilité."],
["5e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il reconnaît une situation de proportionnalité ou de non proportionnalité́ entre deux grandeurs."],
["5e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il partage une quantité en deux ou trois parts selon un ratio donné."],
["5e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il résout des problèmes de proportionnalité dans diverses situations pouvant faire intervenir des pourcentages ou des échelles. Pour cela, il met en œuvre des procédures variées (additivité, homogénéité, passage à l’unité, coefficient de proportionnalité)."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il traduit la relation de dépendance entre deux grandeurs par un tableau de valeur."],
["5e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il produit une formule représentant la dépendance de deux grandeurs."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il effectue des calculs de durées et d’horaires."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le périmètre et l’aire des figures usuelles (rectangle, parallélogramme, triangle, disque)."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le périmètre et l’aire d’un assemblage de figures."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le volume d’un pavé droit, d’un prisme droit, d’un cylindre."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le volume d’un assemblage de ces solides."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il exprime les résultats dans l’unité adaptée."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il vérifie la cohérence des résultats du point de vue des unités pour les calculs de durées, de longueurs, d’aires ou de volumes."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il effectue des conversions d’unités de longueurs, d’aires, de volumes et de durées."],
["5e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il utilise la correspondance entre les unités de volume et de contenance (1 L = 1 dm , 1 000 L = 1 m ) pour effectuer des conversions."],
["5e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il comprend l’effet des symétries (axiale et centrale) : conservation du parallélisme, des longueurs et des angles."],
["5e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il utilise l’échelle d’une carte."],
["5e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il se repère sur une droite graduée et dans le plan muni d’un repère orthogonal."],
["5e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il reconnaît des solides (pavé droit, cube, cylindre, prisme droit, pyramide, cône, boule) à partir d’un objet réel, d’une image, d’une représentation en perspective cavalière."],
["5e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il construit et met en relation une représentation en perspective cavalière et un patron d’un pavé droit, d’un cylindre."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "À partir des connaissances suivantes : - le codage des figures ; - les caractérisations angulaires du parallélisme (angles alternes internes, angles correspondants) ; - la somme des angles d’un triangle ; - l’inégalité triangulaire ; - une définition et une propriété caractéristique du parallélogramme ; - la définition de la médiatrice ; - la définition des hauteurs d’un triangle, il met en œuvre et écrit un protocole de construction de triangles, de parallélogrammes et d’un assemblage de figures."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il transforme une figure par symétrie centrale."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il comprend l’effet des symétries (axiale et centrale) sur des figures : conservation du parallélisme, des longueurs et des angles."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il identifie des symétries dans des frises, des pavages, des rosaces."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mobilise les connaissances des figures, des configurations et des symétries pour déterminer des grandeurs géométriques."],
["5e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mène des raisonnements en utilisant des propriétés des figures, des configurations et des symétries."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il réalise des activités d’algorithmique débranchée."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il met en ordre et/ou complète des blocs fournis par le professeur pour construire un programme simple sur un logiciel de programmation."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit un script de déplacement ou de construction géométrique utilisant des instructions conditionnelles et/ou la boucle « Répéter … fois ». Niveau 2"],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il gère le déclenchement d'un script en réponse à un événement."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit une séquence d’instructions (condition « si … alors » et boucle « répéter … fois »)."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il intègre une variable dans un programme de déplacement, de construction géométrique ou de calcul. Niveau 3"],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il décompose un problème en sous-problèmes et traduit un sous-problème en créant un « bloc-personnalisé »."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il construit une figure en créant un motif et en le reproduisant à l’aide d’une boucle."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il utilise simultanément les boucles « Répéter … fois », et « Répéter jusqu’à … » ainsi que les instructions conditionnelles pour réaliser des figures, des programmes de calculs, des déplacements, des simulations d’expérience aléatoire."],
["5e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit plusieurs scripts fonctionnant en parallèle pour gérer des interactions et créer des jeux."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Manipulation de sommes et différences de nombre relatifs."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Opposé d’un nombre, somme des opposés."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Entretien des tables de multiplication."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Multiplier et diviser par 10, 100, 1 000."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Compléter des multiplications à trou : 5 × ... = 3 ; faire le lien entre multiplication et division."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "a", "Multiplication comme addition itérée : 3 + 3 + 3 + 3 = 4 × 3."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "o", "Multiplier deux nombres relatifs : d’abord dans le cas où un seul des facteurs est négatif, puis, grâce à la distributivité, dans le cas où les deux facteurs sont négatifs."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "o", "Diviser deux nombres relatifs."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "o", "Savoir calculer un enchainement d’opérations avec des nombres relatifs."],
["4e", "Nombres et calculs", "Opérations sur les nombres relatifs", "o", "Utiliser le vocabulaire (somme, quotient, etc.) à partir d’un enchainement d’opérations dans un programme de calcul et inversement."],
["4e", "Nombres et calculs", "Nombres rationnels", "a", "Addition et soustraction de fractions de dénominateurs quelconques mais simples."],
["4e", "Nombres et calculs", "Nombres rationnels", "a", "Comparaison de fractions."],
["4e", "Nombres et calculs", "Nombres rationnels", "a", "Savoir qu’une fraction est aussi le quotient : (le nombre, qui, multiplié par 7 donne 3, donc savoir que 7 × = 3)."],
["4e", "Nombres et calculs", "Nombres rationnels", "a", "Savoir que prendre la fraction d’un nombre revient à multiplier la fraction par ce nombre."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Simplifier une fraction."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Définir la notion de nombre rationnel : le quotient de deux nombres entiers relatifs."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Exprimer l’opposé d’un nombre rationnel."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Calculer le produit de nombres rationnels."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Calculer et représenter la fraction d’une fraction, d’un nombre, d’une quantité."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Définir l’inverse d’un nombre et connaitre sa notation."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Déterminer l’inverse d’une fraction."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Diviser des fractions."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Calculer la valeur d’expressions comportant plusieurs opérations avec des fractions."],
["4e", "Nombres et calculs", "Nombres rationnels", "o", "Résoudre des problèmes mobilisant les opérations sur les fractions : addition, soustraction, multiplication, division, inverse."],
["4e", "Nombres et calculs", "Puissances", "a", "Connaitre et reconnaitre les carrés parfaits des entiers de 0 à 12."],
["4e", "Nombres et calculs", "Puissances", "a", "Multiplier et diviser par 10, 100, 1 000 ; savoir compléter 1 200 = 1,2 × …"],
["4e", "Nombres et calculs", "Puissances", "a", "Puissances simples : 2² = 4 ; 23 = 8 ; 33 = 27."],
["4e", "Nombres et calculs", "Puissances", "o", "Définir les puissances d’exposant positif d’un nombre a."],
["4e", "Nombres et calculs", "Puissances", "o", "Multiplier des puissances d’exposant entier naturel d’un même nombre entre elles."],
["4e", "Nombres et calculs", "Puissances", "o", "Multiplier des puissances d’un même exposant entier naturel de deux nombres entre elles."],
["4e", "Nombres et calculs", "Puissances", "o", "Résoudre des problèmes faisant intervenir des puissances."],
["4e", "Nombres et calculs", "Racine carrée", "a", "Donner les carrés des nombres entiers compris entre 0 et 12."],
["4e", "Nombres et calculs", "Racine carrée", "o", "Comprendre et connaitre la définition de la racine carrée d’un nombre positif."],
["4e", "Nombres et calculs", "Racine carrée", "o", "Encadrer la racine carrée d’un entier par deux nombres entiers consécutifs."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Donner la valeur d’expressions numériques simples."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Résoudre des équations du type a𝑥 = c et 𝑥 + b = c, où a, b et c sont des nombres."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Écrire 3 × 𝑥 sous la forme 3𝑥 et savoir que 3𝑥 c’est 3 × 𝑥."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Connaitre et utiliser : 1 × 𝑥 = 𝑥 ; 𝑥 + 𝑥 = 2𝑥 ; 𝑥 × 𝑥 = 𝑥² ; 3𝑥 + 2𝑥 = 5𝑥 ; 3𝑥 × 2𝑥 = 6𝑥²."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Donner le double, le triple, la moitié, le prédécesseur, le successeur, le carré d’un nombre."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Tester si un nombre vérifie une égalité."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Produire des formules et tester leur vraisemblance : aires de formes géométriques simples, nombres pairs/impairs, etc."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Connaitre et utiliser la distributivité simple pour développer et factoriser une expression algébrique."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Utiliser le calcul algébrique pour produire des démonstrations."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Résoudre une équation du premier degré du type a𝑥 + b = c."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Mettre en équation un problème et le résoudre à l’aide d’une équation du premier degré du type a𝑥 + b = c𝑥 + d."],
["4e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Formuler des conjectures à l’aide d’un algorithme ou d’un tableur pour résoudre de manière exacte ou approchée une équation."],
["4e", "Espace et géométrie", "Transformations", "a", "Construire le symétrique d’un point par demi-tour."],
["4e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Placer sur une droite graduée un point dont l’abscisse est un nombre relatif."],
["4e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Repérer un nombre relatif sur une droite graduée."],
["4e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Dans le plan muni d’un repère orthogonal :\n• lire les coordonnées d’un point donné ;\n• placer un point de coordonnées données."],
["4e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre les solides : cube, pavé, cylindre, prisme droit."],
["4e", "Espace et géométrie", "Représentation de l’espace", "a", "Connaitre et utiliser les formules du volume d’un cube, d’un pavé, d’un prisme, d’un cylindre."],
["4e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre la base d’un prisme donné en perspective cavalière."],
["4e", "Espace et géométrie", "Représentation de l’espace", "a", "Savoir calculer l’aire des figures planes usuelles : triangle, rectangle, disque."],
["4e", "Espace et géométrie", "Représentation de l’espace", "o", "Reconnaitre des solides (pyramide, cône de révolution)."],
["4e", "Espace et géométrie", "Représentation de l’espace", "o", "Construire et mettre en relation différentes représentations des solides (pavé droit, cube, cylindre de révolution, prisme droit, pyramides et cônes de révolution)."],
["4e", "Espace et géométrie", "Représentation de l’espace", "o", "Connaitre le volume de la pyramide et du cône de révolution."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "a", "Dire si des figures planes sont images l’une de l’autre par une symétrie axiale (dont on identifie l’axe) ou par un demi-tour (dont on identifie le centre)."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "a", "Dans une configuration donnée, déterminer les images de figures, de droites, de segments, de points par une symétrie axiale ou un demi-tour."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "a", "Reconnaitre un parallélogramme à l’aide de sa définition ou d’une propriété caractéristique grâce aux codages."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "a", "Reconnaitre un parallélogramme particulier à partir de ses propriétés caractéristiques, notamment à partir des propriétés de ses diagonales."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "o", "Comprendre l’effet d’une translation."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "o", "Faire le lien avec les parallélogrammes, les angles."],
["4e", "Espace et géométrie", "Parallélogrammes et translations", "o", "Connaitre et utiliser les propriétés de conservations des translations."],
["4e", "Espace et géométrie", "Triangles", "a", "Reconnaitre des droites remarquables, y compris dans les triangles particuliers (médiatrices, médianes, hauteurs, bissectrices)."],
["4e", "Espace et géométrie", "Triangles", "o", "Connaitre les trois théorèmes relatifs à la droite des milieux dans un triangle."],
["4e", "Espace et géométrie", "Triangles", "o", "Connaitre le théorème de Pythagore, sa réciproque, sa contraposée."],
["4e", "Espace et géométrie", "Triangles", "o", "Mener un travail de logique sur la réciproque et la contraposée."],
["4e", "Espace et géométrie", "Triangles", "o", "Caractériser un triangle rectangle à l’aide de son cercle circonscrit, par son inscription dans un demi-cercle dont le diamètre est un côté du triangle."],
["4e", "Espace et géométrie", "Triangles", "o", "Déterminer le centre du cercle circonscrit d’un triangle rectangle."],
["4e", "Espace et géométrie", "Triangles", "o", "Construire des rectangles sans équerre."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Calculer une moyenne pour un très petit nombre de valeurs."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Calculer un effectif manquant dans un tableau pour un petit nombre de valeurs."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Calculer une fréquence simple."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Calculer une moyenne pondérée dans le cas d’une série discrète de petits effectifs présentée sous forme de données brutes, d’un tableau ou d’un diagramme en barres."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Déterminer une médiane et l’interpréter dans le cas d’une série de petit effectif présentée sous forme de données brutes."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Calculer et interpréter l’étendue d’une série présentée sous forme de données brutes, d’un tableau, d’un diagramme en barres, d’un diagramme circulaire."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Comprendre l’évolution de la médiane et de la moyenne quand on ajoute une valeur extrême."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Résoudre des problèmes faisant intervenir les différents indicateurs."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Résoudre des problèmes de comparaison de séries statistiques."],
["4e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Utiliser le tableur pour calculer une moyenne, une médiane et l’étendue d’une série statistique."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Utiliser le vocabulaire et les notations ensemblistes pour décrire une expérience aléatoire dans des cas simples et définir la notion d’évènement."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Définir : complémentaire, réunion, intersection, ensemble vide (évènement impossible)."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Calculer la probabilité d’un évènement et de l’évènement contraire."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Exemples simples d’expériences aléatoires à deux épreuves (par exemple, lancer de deux pièces, d’une pièce et d’un dé, de deux dés, etc.)."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "À partir de la répétition d’une expérience aléatoire, réalisée matériellement ou simulée, comparer des graphiques de distributions (fréquentielle et probabiliste)."],
["4e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Observer la fluctuation des fréquences pour un nombre de répétitions fixé de l’expérience aléatoire."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Déterminer a % de c quand a vaut 100, 50, 25, 10, 1."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Compléter : 20 % de 120 = … ; 30 = × 1 000."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Utiliser des grandeurs quotients, avec ou sans unités."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Comparer deux nombres ou deux grandeurs à l’aide de leur rapport ou ratio."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Exprimer la proportionnalité entre deux suites de nombres par des égalités de rapports ou sous forme de ratio."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Déterminer une quatrième proportionnelle."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Calculer avec des pourcentages."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Rendre compte d’une augmentation ou une diminution exprimée en pourcentages au moyen d’un coefficient multiplicateur Définir le coefficient multiplicateur."],
["4e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Résoudre des problèmes de partage proportionnel."],
["4e", "Proportionnalité, fonctions", "Fonctions", "o", "Savoir appliquer un programme de calcul à deux (plusieurs) étapes à un nombre simple puis à une variable."],
["4e", "Proportionnalité, fonctions", "Fonctions", "o", "Savoir retrouver le nombre de départ après avoir remonté un programme de calcul simple."],
["4e", "Proportionnalité, fonctions", "Fonctions", "o", "Produire une formule littérale représentant la dépendance d’une grandeur en fonction d’une autre."],
["4e", "Proportionnalité, fonctions", "Fonctions", "o", "Représenter l’expression d’une grandeur en fonction d’une autre par un graphique."],
["4e", "Proportionnalité, fonctions", "Fonctions", "o", "Comprendre la dépendance d’une grandeur en fonction d’une autre."],
["4e", "La pensée informatique", "Algorithmique", "o", "Représenter des conditions simples."],
["4e", "La pensée informatique", "Algorithmique", "o", "Écrire des instructions conditionnelles."],
["4e", "La pensée informatique", "Algorithmique", "o", "Manipuler une variable."],
["4e", "La pensée informatique", "Algorithmique", "o", "Écrire un programme simple donné pour réaliser un objectif ou résoudre un problème."],
["4e", "La pensée informatique", "Algorithmique", "o", "Modifier un programme donné pour changer son comportement."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il utilise les puissances de 10 d’exposants positifs ou négatifs."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il associe, dans le cas des nombres décimaux, écriture décimale, écriture fractionnaire et notation scientifique."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il utilise les préfixes de nano à giga."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il utilise les carrés parfaits de 1 à 144."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il connaît la définition de la racine carrée d’un nombre positif."],
["4e", "Attendus de fin d’année", "Nombres", "e", "Il utilise les puissances d’exposants strictement positifs d’un nombre pour simplifier l’écriture des produits."],
["4e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il utilise des puissances de 10 pour comparer des nombres."],
["4e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il compare, range et encadre des nombres rationnels (positifs ou négatifs)."],
["4e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il encadre la racine carrée d’un nombre positif entre deux entiers."],
["4e", "Attendus de fin d’année", "Comparaison de nombres", "e", "Il associe à des objets des ordres de grandeur en lien avec d’autres disciplines."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il effectue avec des nombres décimaux relatifs, des produits et des quotients."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il calcule avec les nombres rationnels : addition, soustraction, multiplication, division."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il utilise l’inverse pour calculer."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il résout des problèmes avec des nombres rationnels."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il utilise la calculatrice pour déterminer une valeur approchée de la racine carrée d’un nombre positif."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il utilise la racine carrée d’un nombre positif en lien avec des situations géométriques (théorème de Pythagore ; agrandissement, réduction et aires)."],
["4e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il utilise les ordres de grandeur pour vérifier ses résultats."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il détermine la liste des nombres premiers inférieurs à 100."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il décompose un nombre entier en produit de facteurs premiers."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il utilise les nombres premiers inférieurs à 100 pour : - reconnaître et produire des fractions égales ; - simplifier des fractions."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il modélise et résout des problèmes simples mettant en jeu les notions de divisibilité et de nombre premier."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il identifie la structure d’une expression littérale (somme, produit)."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il utilise la propriété de distributivité simple pour développer un produit, factoriser une somme ou réduire une expression littérale."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il démontre l’équivalence de deux programmes de calcul."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il introduit une lettre pour désigner une valeur inconnue et met un problème en équation."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il teste si un nombre est solution d’une équation."],
["4e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il résout algébriquement une équation du premier degré."],
["4e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il lit, interprète et représente des données sous forme de diagrammes circulaires."],
["4e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il calcule et interprète la médiane d’une série de données de petit effectif total."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il utilise le vocabulaire des probabilités : expérience aléatoire, issues, événement, probabilité, événement certain, événement impossible, événement contraire."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il reconnaît des événements contraires et s’en sert pour calculer des probabilités."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il calcule des probabilités."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il sait que la probabilité d’un événement est un nombre compris entre 0 et 1."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il exprime des probabilités sous diverses formes."],
["4e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il reconnaît sur un graphique une situation de proportionnalité ou de non proportionnalité."],
["4e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il calcule une quatrième proportionnelle par la procédure de son choix."],
["4e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il utilise une formule liant deux grandeurs dans une situation de proportionnalité."],
["4e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il résout des problèmes en utilisant la proportionnalité dans le cadre de la géométrie."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il produit une formule littérale représentant la dépendance de deux grandeurs."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il représente la dépendance de deux grandeurs par un graphique."],
["4e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il utilise un graphique représentant la dépendance de deux grandeurs pour lire et interpréter différentes valeurs sur l’axe des abscisses ou l’axe des ordonnées."],
["4e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le volume d’une pyramide, d’un cône."],
["4e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il effectue des conversions d’unités sur des grandeurs composées."],
["4e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il utilise un rapport d’agrandissement ou de réduction pour calculer, des longueurs, des aires, des volumes."],
["4e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il construit un agrandissement ou une réduction d’une figure donnée."],
["4e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il comprend l’effet d’une translation : conservation du parallélisme, des longueurs, des aires et des angles."],
["4e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il utilise le vocabulaire du repérage : abscisse, ordonnée, altitude."],
["4e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il se repère dans un pavé droit."],
["4e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il construit et met en relation une représentation en perspective cavalière et un patron d’une pyramide, d’un cône de révolution."],
["4e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "À partir des connaissances suivantes : - les cas d’égalité des triangles ; - le théorème de Thalès et sa réciproque dans la configuration des triangles emboîtés ; - le théorème de Pythagore et sa réciproque ; - le cosinus d’un angle d’un triangle rectangle ; - effet d’une translation : conservation du parallélisme, des longueurs, des aires et des angles, il met en œuvre et écrit un protocole de construction de figures."],
["4e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il transforme une figure par translation."],
["4e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il identifie des translations dans des frises et des pavages."],
["4e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mobilise les connaissances des figures, des configurations et de la translation pour déterminer des grandeurs géométriques."],
["4e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mène des raisonnements en utilisant des propriétés des figures, des configurations et de la translation."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il réalise des activités d’algorithmique débranchée."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il met en ordre et/ou complète des blocs fournis par le professeur pour construire un programme simple sur un logiciel de programmation."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit un script de déplacement ou de construction géométrique utilisant des instructions conditionnelles et/ou la boucle « Répéter … fois ». Niveau 2"],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il gère le déclenchement d'un script en réponse à un événement."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit une séquence d’instructions (condition « si … alors » et boucle « répéter … fois »)."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il intègre une variable dans un programme de déplacement, de construction géométrique ou de calcul. Niveau 3"],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il décompose un problème en sous-problèmes et traduit un sous-problème en créant un « bloc-personnalisé »."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il construit une figure en créant un motif et en le reproduisant à l’aide d’une boucle."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il utilise simultanément les boucles « Répéter … fois », et « Répéter jusqu’à … » ainsi que les instructions conditionnelles pour réaliser des figures, des programmes de calculs, des déplacements, des simulations d’expérience aléatoire."],
["4e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit plusieurs scripts fonctionnant en parallèle pour gérer des interactions et créer des jeux."],
["3e", "Nombres et calculs", "Nombres rationnels", "a", "Additionner, soustraire, multiplier et diviser des fractions."],
["3e", "Nombres et calculs", "Nombres rationnels", "o", "Mettre une fraction sous forme irréductible."],
["3e", "Nombres et calculs", "Nombres rationnels", "o", "Rendre irréductible une fraction."],
["3e", "Nombres et calculs", "Nombres rationnels", "o", "Résoudre des problèmes faisant appel à des fractions."],
["3e", "Nombres et calculs", "Puissances", "a", "Puissance comme multiplication itérée : 3 × 3 × 3 × 3 = 34."],
["3e", "Nombres et calculs", "Puissances", "a", "Multiplication de puissances d’exposant positif d’un nombre."],
["3e", "Nombres et calculs", "Puissances", "a", "Multiplication de puissances de même exposant positif de deux nombres."],
["3e", "Nombres et calculs", "Puissances", "o", "Définir les puissances d’exposant négatif d’un nombre."],
["3e", "Nombres et calculs", "Puissances", "o", "Multiplier et diviser des puissances."],
["3e", "Nombres et calculs", "Puissances", "o", "Déterminer la notation scientifique d’un nombre."],
["3e", "Nombres et calculs", "Puissances", "o", "Résoudre des problèmes notamment en utilisant la notation scientifique."],
["3e", "Nombres et calculs", "Racine carrée", "a", "Donner les carrés des nombres entiers compris entre 0 et 12."],
["3e", "Nombres et calculs", "Racine carrée", "o", "Résoudre analytiquement et graphiquement des équations de la forme 𝑥2 = a."],
["3e", "Nombres et calculs", "Racine carrée", "o", "Résoudre des problèmes utilisant la racine carrée."],
["3e", "Nombres et calculs", "Multiples et diviseurs", "a", "Factoriser un nombre entier positif : 60 = 2² × 3 × 5."],
["3e", "Nombres et calculs", "Multiples et diviseurs", "a", "Simplifier une fraction dont le numérateur et le dénominateur sont dans une même table de multiplication, par exemple"],
["3e", "Nombres et calculs", "Multiples et diviseurs", "a", "Trouver un dénominateur commun à deux fractions pour les additionner, les soustraire ou les comparer."],
["3e", "Nombres et calculs", "Multiples et diviseurs", "a", "Appliquer les critères de divisibilité par 2, 3, 5, 9."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Résoudre des équations du type a𝑥 = c, 𝑥 + b = c, a𝑥 + b = c."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Simplifier des expressions littérales."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Calculer la valeur d’une expression algébrique avec des puissances ou non."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Donner la nature d’une expression littérale : 3𝑥 + 2 est une somme, 5 (𝑥 + 4) est un produit."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Développer et factoriser une expression simple."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Donner l’expression générique d’un nombre pair, d’un nombre impair."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "a", "Prendre l’opposé d’une expression : savoir que – (5 – 4𝑥) = –5 + 4𝑥."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Simplifier des expressions produits ou des rapports comportant des facteurs communs."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Utiliser la double distributivité pour développer et factoriser des expressions dont le facteur est apparent."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Résoudre analytiquement et graphiquement une inéquation du premier degré du type a𝑥 ⩾ b."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Résoudre une équation produit nul."],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Manipuler les trois identités remarquables pour développer et factoriser :"],
["3e", "Nombres et calculs", "Calcul littéral et algébrique", "o", "Pratiquer un raisonnement par analyse-synthèse dans le cadre d’une résolution d’équation."],
["3e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Placer sur une droite graduée un point dont l’abscisse est un nombre relatif."],
["3e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Repérer un nombre relatif sur une droite graduée."],
["3e", "Espace et géométrie", "Repérage sur une droite et dans le plan", "a", "Dans le plan muni d’un repère orthogonal :\n• lire les coordonnées d’un point donné ;\n• placer un point de coordonnées données."],
["3e", "Espace et géométrie", "Représentation de l’espace", "a", "Reconnaitre des solides (pavé droit, cube, prisme droit, cylindre, pyramide, cône)."],
["3e", "Espace et géométrie", "Représentation de l’espace", "a", "Connaitre et utiliser les formules du volume d’une pyramide ou d’un cône."],
["3e", "Espace et géométrie", "Représentation de l’espace", "a", "Donner la nature d’une face d’une pyramide représentée en perspective cavalière."],
["3e", "Espace et géométrie", "Représentation de l’espace", "a", "Identifier les patrons de pyramides données (par exemple inscrites dans un cube)."],
["3e", "Espace et géométrie", "Représentation de l’espace", "o", "Définir la boule et la sphère."],
["3e", "Espace et géométrie", "Représentation de l’espace", "o", "Définir les grands cercles, le diamètre."],
["3e", "Espace et géométrie", "Représentation de l’espace", "o", "Visualiser et réaliser des sections de pavé parallèlement à une face, de cylindre parallèlement ou perpendiculairement à son axe, d’une boule."],
["3e", "Espace et géométrie", "Représentation de l’espace", "o", "Connaitre et utiliser la formule du volume d’une boule de rayon donné."],
["3e", "Espace et géométrie", "Triangles", "a", "Utiliser la propriété du triangle rectangle et de son cercle circonscrit."],
["3e", "Espace et géométrie", "Triangles", "a", "Écrire l’égalité de Pythagore dans un triangle rectangle."],
["3e", "Espace et géométrie", "Triangles", "a", "Utiliser la droite des milieux pour prouver que des droites sont parallèles, pour calculer une longueur, pour prouver qu’un point est le milieu d’un côté."],
["3e", "Espace et géométrie", "Triangles", "o", "Connaitre et appliquer le théorème de Thalès, sa réciproque, sa contraposée (configurations des triangles emboités et configuration dite du papillon)."],
["3e", "Espace et géométrie", "Triangles", "o", "Connaitre et utiliser les lignes trigonométriques dans le triangle rectangle : cosinus, sinus, tangente."],
["3e", "Espace et géométrie", "Translations et vecteurs", "a", "Mobiliser les connaissances sur la symétrie axiale, le demi-tour, la translation."],
["3e", "Espace et géométrie", "Translations et vecteurs", "o", "Définir et utiliser la translation : définition ponctuelle avec parallélogramme."],
["3e", "Espace et géométrie", "Translations et vecteurs", "o", "Définir et utiliser les notions de vecteur, de vecteurs égaux, de vecteur nul, d’opposé d’un vecteur."],
["3e", "Espace et géométrie", "Translations et vecteurs", "o", "Définir et utiliser la somme de deux vecteurs par enchainement de deux translations."],
["3e", "Espace et géométrie", "Translations et vecteurs", "o", "Découvrir et utiliser la relation de Chasles."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Calculer une moyenne."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Donner une médiane pour une série comportant un petit nombre de valeurs."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "a", "Calculer l’étendue d’une série."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Calculer des effectifs cumulés croissants."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Donner les quartiles et la médiane d’une série donnée sous forme de tableau d’effectifs ou de diagramme en barres."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Construire et utiliser des boites à moustache pour représenter les valeurs de position d’une série statistique."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Comprendre et interpréter des données statistiques."],
["3e", "Organisation et gestion de données et probabilités", "Statistiques", "o", "Utiliser le tableur pour calculer une moyenne, une médiane et l’étendue d’une série statistique."],
["3e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Connaitre et savoir appliquer la relation 𝑃(𝐴 ∪ 𝐵) + 𝑃(𝐴 ∩ 𝐵) = 𝑃(𝐴) + 𝑃(𝐵)."],
["3e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Simuler des expériences aléatoires indépendantes."],
["3e", "Organisation et gestion de données et probabilités", "Probabilités", "o", "Observer la stabilisation des fréquences lorsqu’on augmente le nombre de répétitions de l’expérience aléatoire, faire le lien entre fréquence et probabilité selon le nombre de répétitions."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Partager une somme en deux parts selon un certain ratio."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Partager une masse en trois parts selon un certain ratio."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Partager une somme entre deux personnes âgées de 20 et 30 ans proportionnellement à leur âge."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Calculer le pourcentage d’une quantité."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Calculer la distance réelle entre deux villes, connaissant la distance entre ces villes sur une carte routière dont l’échelle est connue."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "a", "Appliquer, dans des cas simples, une augmentation ou une diminution exprimée en pourcentages, en utilisant ou non le coefficient multiplicateur."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Traduire une augmentation ou une diminution en pourcentages."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Relier la représentation graphique d’une situation de proportionnalité avec le théorème de Thalès."],
["3e", "Proportionnalité, fonctions", "Proportionnalité", "o", "Connaitre et utiliser les fonctions linéaires."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Utiliser les différentes représentations d’une fonction."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Définir et connaitre le vocabulaire : image, antécédents."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Définir et utiliser les fonctions linéaires."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Résoudre graphiquement des équations et des inéquations linéaires."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Relier fonctions linéaires et proportionnalité."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Définir et utiliser les fonctions affines."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Déterminer graphiquement les coefficients d’une fonction affine."],
["3e", "Proportionnalité, fonctions", "Fonctions", "o", "Représenter la fonction carré."],
["3e", "La pensée informatique", "Algorithmique", "o", "Approfondir la notion de variables."],
["3e", "La pensée informatique", "Algorithmique", "o", "Utiliser des conditions composées."],
["3e", "La pensée informatique", "Algorithmique", "o", "Utiliser une boucle conditionnelle."],
["3e", "La pensée informatique", "Algorithmique", "o", "Structurer des programmes."],
["3e", "La pensée informatique", "Algorithmique", "o", "Écrire un programme donné pour réaliser un objectif ou résoudre un problème."],
["3e", "Attendus de fin d’année", "Nombres", "e", "Il utilise les puissances d’exposants positifs ou négatifs pour simplifier l’écriture des produits."],
["3e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il calcule avec les nombres rationnels, notamment dans le cadre de résolution de problèmes."],
["3e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il résout des problèmes mettant en jeu des racines carrées."],
["3e", "Attendus de fin d’année", "Pratiquer le calcul exact ou approché, mental, à la main ou instrumenté", "e", "Il résout des problèmes avec des puissances, notamment en utilisant la notation scientifique."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il décompose un nombre entier en produit de facteurs premiers (à la main, à l’aide d’un tableur ou d’un logiciel de programmation)."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il simplifie une fraction pour la rendre irréductible."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser les notions de divisibilité et de nombres premiers", "e", "Il modélise et résout des problèmes mettant en jeu la divisibilité (engrenages, conjonction de phénomènes…)."],
["3e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il détermine l’opposé d’une expression littérale."],
["3e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il développe (par simple et double distributivités), factorise, réduit des expressions algébriques simples."],
["3e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il factorise une expression du type a - b et développe des expression du type (a + b)(a - b)."],
["3e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il résout algébriquement différents types d’équations : - équation du premier degré ; - équation s’y ramenant (équations produits) ; - équations de la forme x = a sur des exemples simples."],
["3e", "Attendus de fin d’année", "Utiliser le calcul littéral", "e", "Il résout des problèmes s’y ramenant, qui peuvent être internes aux mathématiques ou en lien avec d’autres disciplines."],
["3e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il lit, interprète et représente des données sous forme d’histogrammes pour des classes de même amplitude."],
["3e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il calcule et interprète l’étendue d’une série présentée sous forme de données brutes, d’un tableau, d’un diagramme en bâtons, d’un diagramme circulaire ou d’un histogramme."],
["3e", "Attendus de fin d’année", "Interpréter, représenter et traiter des données", "e", "Il calcule des effectifs et des fréquences."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "À partir de dénombrements, il calcule des probabilités pour des expériences aléatoires simples à une ou deux épreuves."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser des notions élémentaires de probabilités", "e", "Il fait le lien entre stabilisation des fréquences et probabilités."],
["3e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il modélise une situation de proportionnalité à l’aide d’une fonction linéaire."],
["3e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il utilise le lien entre pourcentage d’évolution et coefficient multiplicateur."],
["3e", "Attendus de fin d’année", "Résoudre des problèmes de proportionnalité", "e", "Il résout des problèmes en utilisant la proportionnalité dans le cadre de la géométrie."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il utilise les notations et le vocabulaire fonctionnels."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il passe d’un mode de représentation d’une fonction à un autre."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il détermine, à partir de tous les modes de représentation, l’image d’un nombre."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il détermine un antécédent à partir d‘une représentation graphique ou d’un tableau de valeurs d’une fonction."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il détermine de manière algébrique l’antécédent par une fonction, dans des cas se ramenant à la résolution d’une équation du premier degré."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il représente graphiquement une fonction linéaire, une fonction affine."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il interprète les paramètres d’une fonction affine suivant l’allure de sa courbe représentative."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il modélise un phénomène continu par une fonction."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il modélise une situation de proportionnalité à l’aide d’une fonction linéaire."],
["3e", "Attendus de fin d’année", "Comprendre et utiliser la notion de fonction", "e", "Il résout des problèmes modélisés par des fonctions en utilisant un ou plusieurs modes de représentation."],
["3e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule le volume d’une boule."],
["3e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il calcule les volumes d’assemblages de solides étudiés au cours du cycle."],
["3e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il mène des calculs sur des grandeurs mesurables, notamment des grandeurs composées, et exprime les résultats dans les unités adaptées."],
["3e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il résout des problèmes utilisant les conversions d’unités sur des grandeurs composées."],
["3e", "Attendus de fin d’année", "Calculer avec des grandeurs mesurables ; exprimer les résultats dans les unités adaptées", "e", "Il vérifie la cohérence des résultats du point de vue des unités pour les calculs de grandeurs simples ou composées."],
["3e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il calcule des grandeurs géométriques (longueurs, aires et volumes) en utilisant les transformations (symétries, rotations, translations, homothétie)."],
["3e", "Attendus de fin d’année", "Comprendre l’effet de quelques transformations sur les figures géométriques", "e", "Il résout des problèmes en utilisant la proportionnalité en géométrie dans le cadre de certaines configurations ou transformations (agrandissement, réduction, triangles semblables, homothéties)."],
["3e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il se repère sur une sphère (latitude, longitude)."],
["3e", "Attendus de fin d’année", "Représenter l’espace", "e", "Il construit et met en relation différentes représentations des solides étudiés au cours du cycle (représentations en perspective cavalière, vues de face, de dessus, en coupe, patrons) et leurs sections planes."],
["3e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "À partir des connaissances suivantes : - le théorème de Thalès et sa réciproque dans la configuration papillon ; - les triangles semblables : une définition et une propriété caractéristique ; - les lignes trigonométriques dans le triangle rectangle : cosinus, sinus, tangente, il transforme une figure par rotation et par homothétie et il comprend l’effet d’une rotation et d’une homothétie."],
["3e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il identifie des rotations et des homothéties dans des frises, des pavages et des rosaces."],
["3e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mobilise les connaissances des figures, des configurations, de la rotation et de l’homothétie pour déterminer des grandeurs géométriques."],
["3e", "Attendus de fin d’année", "Utiliser les notions de géométrie plane pour démontrer", "e", "Il mène des raisonnements en utilisant des propriétés des figures, des configurations, de la rotation et de l’homothétie."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il réalise des activités d’algorithmique débranchée."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il met en ordre et/ou complète des blocs fournis par le professeur pour construire un programme simple sur un logiciel de programmation."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit un script de déplacement ou de construction géométrique utilisant des instructions conditionnelles et/ou la boucle « Répéter … fois ». Niveau 2"],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il gère le déclenchement d'un script en réponse à un événement."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit une séquence d’instructions (condition « si … alors » et boucle « répéter … fois »)."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il intègre une variable dans un programme de déplacement, de construction géométrique ou de calcul. Niveau 3"],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il décompose un problème en sous-problèmes et traduit un sous-problème en créant un « bloc-personnalisé »."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il construit une figure en créant un motif et en le reproduisant à l’aide d’une boucle."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il utilise simultanément les boucles « Répéter … fois » et « Répéter jusqu’à … » ainsi que les instructions conditionnelles pour réaliser des figures, des programmes de calculs, des déplacements, des simulations d’expérience aléatoire."],
["3e", "Attendus de fin d’année", "Écrire, mettre au point, exécuter un programme", "e", "Il écrit plusieurs scripts fonctionnant en parallèle pour gérer des interactions et créer des jeux."]
];
