/* Programme de mathématiques du cycle 3 – classe de 6e (objectifs d'apprentissage). Format : [niveau, domaine, thème, type, texte] */
(self.BO_DATA=self.BO_DATA||[]).push(
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Connaître et utiliser la valeur des chiffres selon leur rang dans l’écriture d’un nombre"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Connaître les liens entre les unités de numération unité, dizaine, centaine, millier, dixième, centième, millième"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Connaître des grands nombres entiers"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Reconnaître un nombre décimal"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Connaître la définition d’un pourcentage"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Associer et utiliser différentes écritures d’un nombre décimal : écriture à virgule, fraction, nombre mixte, pourcentage"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Placer sur une demi-droite graduée un point dont l’abscisse est un nombre décimal"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Repérer un nombre décimal sur une demi-droite graduée"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Comparer deux nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Ordonner une liste de nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Donner la valeur arrondie à l’unité, au dixième ou au centième, d’un nombre décimal"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Déterminer ou connaître la valeur arrondie de certains nombres non décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Encadrer un nombre décimal par deux nombres décimaux, intercaler un nombre décimal entre deux nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Additionner et soustraire des nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Multiplier un nombre entier ou un nombre décimal par 0,1, par 0,01, et par 0,001"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Connaître le lien avec la division par 10, 100 et par 1 000"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Comprendre le sens de la multiplication de deux nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Calculer le produit de deux nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Contrôler les résultats à l’aide d’ordres de grandeur"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Résoudre des problèmes mettant en jeu des multiplications entre des nombres décimaux"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Diviser un nombre décimal par un nombre entier non nul inférieur à 10"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Résoudre des problèmes mettant en jeu des divisions décimales"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Effectuer la division euclidienne d’un nombre entier par un nombre entier inférieur à 100"],
["6e", "Nombres, calcul et résolution de problèmes", "Les nombres entiers et décimaux", "o", "Résoudre des problèmes mettant en jeu des divisions euclidiennes"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Relier une fraction au résultat exact de la division de son numérateur par son dénominateur"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Comprendre et connaître la définition du quotient d’un entier a par un entier b non nul"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Compléter des égalités à trous multiplicatives"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Placer une fraction sur une demi-droite graduée dans des cas simples"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Graduer un segment de longueur donnée a"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Le sens quotient d’une fraction", "o", "Savoir que la fraction peut représenter un nombre entier, un nombre décimal non entier ou un nombre non décimal b"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › La fraction comme opérateur multiplicatif", "o", "Utiliser une multiplication pour appliquer une fraction à un nombre entier"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Comparer des fractions", "o", "Établir des égalités de fractions"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Comparer des fractions", "o", "Comparer et encadrer des fractions"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Comparer des fractions", "o", "Ordonner une liste de nombres écrits sous forme de fractions ou de nombres mixtes"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Effectuer des opérations sur les fractions", "o", "Additionner et soustraire des fractions"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Effectuer des opérations sur les fractions", "o", "Multiplier une fraction par un nombre entier"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Effectuer des opérations sur les fractions", "o", "Résoudre des problèmes mettant en jeu des fractions"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Effectuer des opérations sur les fractions", "o", "Inventer des problèmes mettant en jeu des fractions"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Pourcentages", "o", "Comprendre le sens d’un pourcentage"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Pourcentages", "o", "Calculer une proportion (rapport entre une partie et le tout) et l’exprimer sous forme de pourcentage dans des cas simples"],
["6e", "Nombres, calcul et résolution de problèmes", "Les fractions › Pourcentages", "o", "Appliquer un pourcentage à une grandeur ou à un nombre"],
["6e", "Nombres, calcul et résolution de problèmes", "Algèbre › Résoudre des problèmes mettant en jeu des nombres inconnus", "o", "Utiliser des modèles pré-algébriques pour résoudre des problèmes algébriques"],
["6e", "Nombres, calcul et résolution de problèmes", "Algèbre › Résoudre des problèmes mettant en jeu des nombres inconnus", "o", "Identifier la structure d’un motif évolutif en repérant une régularité et en identifiant une structure"],
["6e", "Grandeurs et mesures", "Les longueurs", "o", "Savoir que le périmètre du disque est proportionnel à son diamètre"],
["6e", "Grandeurs et mesures", "Les longueurs", "o", "Connaître la formule du périmètre d’un disque"],
["6e", "Grandeurs et mesures", "Les longueurs", "o", "Calculer le périmètre d’un disque"],
["6e", "Grandeurs et mesures", "Les longueurs", "o", "Calculer des périmètres de figures composées"],
["6e", "Grandeurs et mesures", "Les longueurs", "o", "Résoudre des problèmes impliquant des longueurs"],
["6e", "Grandeurs et mesures", "Les aires", "o", "Effectuer des conversions d’aire"],
["6e", "Grandeurs et mesures", "Les aires", "o", "Connaître la formule de l’aire d’un carré ou d’un rectangle"],
["6e", "Grandeurs et mesures", "Les aires", "o", "Calculer l’aire d’un carré ou d’un rectangle"],
["6e", "Grandeurs et mesures", "Les aires", "o", "1"],
["6e", "Grandeurs et mesures", "Les aires", "o", "100"],
["6e", "Grandeurs et mesures", "Les aires", "o", "1"],
["6e", "Grandeurs et mesures", "Les aires", "o", "100 dm2 ou 1 cm2 = 0,01 dm2. m2 ou 1 dm² = 0,01 m2."],
["6e", "Grandeurs et mesures", "Les volumes", "o", "Connaître l’unité centimètre cube"],
["6e", "Grandeurs et mesures", "Les volumes", "o", "Comparer des volumes"],
["6e", "Grandeurs et mesures", "Les volumes", "o", "Déterminer un volume"],
["6e", "Grandeurs et mesures", "Le repérage dans le temps et les durées", "o", "Effectuer des calculs sur des horaires et des durées"],
["6e", "Grandeurs et mesures", "Le repérage dans le temps et les durées", "o", "Résoudre des problèmes impliquant des horaires et des durées"],
["6e", "Grandeurs et mesures", "Le repérage dans le temps et les durées", "o", "Convertir des durées"],
["6e", "Espace et géométrie", "Étude de configurations planes › Distances", "o", "Connaître et utiliser la définition de la distance entre deux points"],
["6e", "Espace et géométrie", "Étude de configurations planes › Distances", "o", "Connaître et utiliser la définition du milieu d’un segment"],
["6e", "Espace et géométrie", "Étude de configurations planes › Cercles et disques", "o", "Connaître les définitions d’un cercle, d’un disque, d’un rayon, d’un diamètre, d’une corde"],
["6e", "Espace et géométrie", "Étude de configurations planes › Cercles et disques", "o", "Comprendre la définition d’un cercle et celle d’un disque sous la forme d’ensembles de points"],
["6e", "Espace et géométrie", "Étude de configurations planes › Cercles et disques", "o", "Résoudre des problèmes mettant en jeu des distances à un point"],
["6e", "Espace et géométrie", "Étude de configurations planes › Médiatrice d’un segment", "o", "Connaître la définition de la médiatrice d’un segment"],
["6e", "Espace et géométrie", "Étude de configurations planes › Médiatrice d’un segment", "o", "Comprendre et utiliser la propriété caractéristique de la médiatrice d’un segment"],
["6e", "Espace et géométrie", "Étude de configurations planes › Médiatrice d’un segment", "o", "Résoudre des problèmes en s’appuyant sur la propriété caractéristique de la médiatrice"],
["6e", "Espace et géométrie", "Étude de configurations planes › Angles", "o", "Connaître et utiliser les angles ainsi que le lexique et les notations qui s’y rapportent : angle droit, angle plat, angle plein, angle nul, angle aigu, angle obtus, angles opposés par le sommet, angles adjacents, angles supplémentaires"],
["6e", "Espace et géométrie", "Étude de configurations planes › Angles", "o", "Mesurer un angle"],
["6e", "Espace et géométrie", "Étude de configurations planes › Angles", "o", "Construire un angle de mesure donnée"],
["6e", "Espace et géométrie", "Étude de configurations planes › Bissectrice d’un angle saillant", "o", "Connaître la définition de la bissectrice d’un angle saillant"],
["6e", "Espace et géométrie", "Étude de configurations planes › Bissectrice d’un angle saillant", "o", "Utiliser la définition de la bissectrice d’un angle pour effectuer des constructions et résoudre des problèmes"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "Construire des triangles"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "Connaître et utiliser les propriétés angulaires des triangles particuliers : triangle rectangle, triangle isocèle, triangle équilatéral"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "Connaître la valeur de la somme des mesures des angles d’un triangle"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "L’utiliser pour calculer des angles, effectuer des constructions et résoudre des problèmes"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "Savoir que les médiatrices d’un triangle sont concourantes"],
["6e", "Espace et géométrie", "Étude de configurations planes › Triangles", "o", "Connaître et construire le cercle circonscrit à un triangle"],
["6e", "Espace et géométrie", "Étude de configurations planes › Symétrie axiale", "o", "Connaître la définition du symétrique d’un point par rapport à une droite"],
["6e", "Espace et géométrie", "Étude de configurations planes › Symétrie axiale", "o", "Connaître et utiliser les propriétés de la symétrie axiale pour effectuer des constructions"],
["6e", "Espace et géométrie", "La vision dans l’espace", "o", "Voir dans l’espace des assemblages de cubes"],
["6e", "Organisation et gestion de données et probabilités", "Organisation et gestion de données", "o", "Planifier une enquête et recueillir des données"],
["6e", "Organisation et gestion de données et probabilités", "Organisation et gestion de données", "o", "Réaliser des mesures et les consigner dans un tableau"],
["6e", "Organisation et gestion de données et probabilités", "Organisation et gestion de données", "o", "Construire un tableau simple pour présenter des données (observations, caractères)"],
["6e", "Organisation et gestion de données et probabilités", "Organisation et gestion de données", "o", "Faire un choix en filtrant les données d’un tableau selon un critère"],
["6e", "Organisation et gestion de données et probabilités", "Les probabilités", "o", "Savoir que la probabilité d’un évènement est un nombre compris entre 0 et 1"],
["6e", "Organisation et gestion de données et probabilités", "Les probabilités", "o", "Calculer des probabilités dans des situations simples d’équiprobabilité"],
["6e", "Organisation et gestion de données et probabilités", "Les probabilités", "o", "Comparer des résultats d’une expérience aléatoire répétée à une probabilité calculée"],
["6e", "La proportionnalité", "La proportionnalité", "o", "Connaître la définition de la proportionnalité entre deux grandeurs et la mettre en lien avec des expressions de la vie courante"],
["6e", "La proportionnalité", "La proportionnalité", "o", "Identifier si une situation relève du « modèle » de la proportionnalité"],
["6e", "La proportionnalité", "La proportionnalité", "o", "Résoudre un problème de proportionnalité en choisissant une procédure adaptée : propriété de linéarité pour la multiplication ou l’addition, retour à l’unité"],
["6e", "La proportionnalité", "La proportionnalité", "o", "Représenter une situation de proportionnalité à l’aide d’un tableau ou de notations symboliques"],
["6e", "La proportionnalité", "La proportionnalité", "o", "S’initier à la résolution de problèmes d’échelles"],
["6e", "Initiation à la pensée informatique", "Initiation à la pensée informatique", "o", "Identifier une instruction ou une séquence d’instructions"],
["6e", "Initiation à la pensée informatique", "Initiation à la pensée informatique", "o", "Produire et exécuter une séquence d’instructions"],
["6e", "Initiation à la pensée informatique", "Initiation à la pensée informatique", "o", "Répéter à la main une séquence d’instructions pour accomplir une tâche imposée"],
["6e", "Initiation à la pensée informatique", "Initiation à la pensée informatique", "o", "Programmer la construction d’un chemin simple"]
);
