/* Programme de mathématiques intégré à l'enseignement scientifique (1re générale) + mon bilan des compétences par chapitre. Format : [niveau, domaine, thème, type (c=contenu, o=capacité, a=automatisme, e=attendu), texte] */
(self.BO_DATA=self.BO_DATA||[]).push(
["1re (ens. scientifique)", "Programme", "Analyse de l'information chiffrée", "c", "Analyse statistique de deux caractères qualitatifs : tableau croisé d’effectifs, représentations graphiques (diagrammes en barres, circulaires)."],
["1re (ens. scientifique)", "Programme", "Analyse de l'information chiffrée", "c", "Analyse statistique de deux caractères quantitatifs : nuage de points, ajustement affine, point moyen, interpolation, extrapolation."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "c", "Probabilité conditionnelle."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "c", "Indépendance de deux évènements."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "c", "Probabilité associée à la répétition d’épreuves aléatoires identiques et indépendantes de Bernoulli."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "c", "Suites arithmétiques : définition par la relation de récurrence, explicitation du terme de rang n, sens de variation, représentation graphique."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "c", "Fonctions affines : représentation graphique, sens de variation, lien entre taux d’accroissement et coefficient directeur."],
["1re (ens. scientifique)", "Programme", "Modélisation quadratique", "c", "Fonctions polynômes de degré 2 : allure de la courbe, axe de symétrie, coordonnées du sommet, tableau de variation."],
["1re (ens. scientifique)", "Programme", "Modélisation quadratique", "c", "Racines et signe d’un polynôme de degré 2 donné sous forme factorisée (le discriminant ne figure pas au programme)."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "c", "Suites géométriques à termes strictement positifs : définition par récurrence, terme de rang n, sens de variation, représentation graphique."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "c", "Fonctions exponentielles : introduction de x ↦ a^x (a > 0, x ⩾ 0), propriétés algébriques (admises), variations, représentation graphique."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "c", "Cas particulier de l’exposant 1/n."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "c", "Taux d’évolution moyen correspondant à n évolutions successives."],
["1re (ens. scientifique)", "Automatismes", "Évolutions et variations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Évolutions et variations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Évolutions et variations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Évolutions et variations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Calcul numérique et algébrique", "a", "Déterminer les solutions d’une équation produit nul."],
["1re (ens. scientifique)", "Automatismes", "Calcul numérique et algébrique", "a", "Déterminer le signe d’une expression du premier degré, d’une expression factorisée du second degré."],
["1re (ens. scientifique)", "Automatismes", "Calcul numérique et algébrique", "a", "Développer, factoriser, réduire une expression algébrique simple."],
["1re (ens. scientifique)", "Automatismes", "Fonctions et représentations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Fonctions et représentations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Fonctions et représentations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Fonctions et représentations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Fonctions et représentations", "a", ""],
["1re (ens. scientifique)", "Automatismes", "Statistiques", "a", "Lire un graphique, un histogramme, un diagramme en barres ou circulaire, un diagramme en boite ou toute autre représentation (repérer l’origine du repère, les unités de graduations ou les échelles, etc.)."],
["1re (ens. scientifique)", "Automatismes", "Statistiques", "a", "Passer du graphique aux données et vice-versa."],
["1re (ens. scientifique)", "Automatismes", "Statistiques", "a", "Calculer et interpréter des indicateurs statistiques pour une série statistique."],
["1re (ens. scientifique)", "Automatismes", "Probabilités", "a", "Calculer des probabilités conditionnelles lorsque les évènements sont présentés sous forme de tableau croisé d’effectifs ou d’arbres pondérés."],
["1re (ens. scientifique)", "Automatismes", "Probabilités", "a", "Distinguer P(A ∩ B), PA (B), PB (A)."],
["1re (ens. scientifique)", "Programme", "Analyse de l'information chiffrée", "o", "Utiliser un tableur pour représenter des données sous forme de tableau ou de diagramme."],
["1re (ens. scientifique)", "Programme", "Analyse de l'information chiffrée", "o", "Déterminer et utiliser un ajustement affine pour interpoler ou extrapoler des valeurs inconnues."],
["1re (ens. scientifique)", "Programme", "Analyse de l'information chiffrée", "o", "Savoir calculer les coordonnées d’un point moyen."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "o", "Calculer des probabilités conditionnelles à l'aide d'un tableau croisé d'effectifs ou d'un arbre pondéré."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "o", "Représenter par un arbre de probabilités la répétition de n épreuves aléatoires identiques et indépendantes de Bernoulli avec n ⩽ 4 afin de calculer des probabilités."],
["1re (ens. scientifique)", "Programme", "Phénomènes aléatoires", "o", "Savoir utiliser ou justifier l’indépendance de deux évènements."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "o", "Reconnaitre un phénomène discret ou continu de croissance linéaire et savoir le modéliser."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "o", "Calculer un terme de rang donné d'une suite arithmétique définie par une relation fonctionnelle ou une relation de récurrence."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "o", "Réaliser et exploiter la représentation graphique des termes d'une suite arithmétique ou d'une fonction affine."],
["1re (ens. scientifique)", "Programme", "Variation linéaire", "o", "Résoudre un problème de seuil dans le cas d'une croissance linéaire."],
["1re (ens. scientifique)", "Programme", "Modélisation quadratique", "o", "Associer une parabole à une expression algébrique de degré 2, pour les fonctions de la forme : 𝑥 ↦ a𝑥², 𝑥 ↦ a𝑥² + c, 𝑥 ↦ a (𝑥 – 𝑥1) (𝑥 – 𝑥2)."],
["1re (ens. scientifique)", "Programme", "Modélisation quadratique", "o", "Déterminer des éléments caractéristiques de la fonction 𝑥 ↦ a𝑥² + b𝑥 + c. Aucune formule n’est attendue. On déterminera l’axe de symétrie par exemple en résolvant l’équation ƒ (𝑥) = c."],
["1re (ens. scientifique)", "Programme", "Modélisation quadratique", "o", "Utiliser la forme factorisée (en produit de facteurs du premier degré) d’un polynôme de degré 2 pour trouver ses racines et étudier son signe."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Reconnaitre un phénomène discret ou continu de croissance ou décroissance exponentielle et savoir le modéliser."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Calculer un terme de rang donné d'une suite géométrique définie par une relation fonctionnelle ou une relation de récurrence."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Calculer un taux d'évolution moyen."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Réaliser et exploiter la représentation graphique des termes d'une suite géométrique ou d'une fonction exponentielle."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Estimer les ordres de grandeur d’une quantité en croissance ou décroissance exponentielle."],
["1re (ens. scientifique)", "Programme", "Variation exponentielle", "o", "Résoudre un problème de seuil dans le cas d'une croissance ou décroissance exponentielle par le calcul, à l'aide d'une représentation graphique ou en utilisant un outil numérique."],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap A : Analyse de l’Information chiffrée › I.​ TABLEAU CROISE D’EFFECTIF", "o", "​ je sais construire et compléter un tableau croisé d’effectifs"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap A : Analyse de l’Information chiffrée › II.​ REPRESENTATION GRAPHIQUE DES DONNEES", "o", "​ tracer et exploiter un diagramme en bâtons"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap A : Analyse de l’Information chiffrée › II.​ REPRESENTATION GRAPHIQUE DES DONNEES", "o", "​ tracer et exploiter un diagramme circulaire"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap A : Analyse de l’Information chiffrée › II.​ REPRESENTATION GRAPHIQUE DES DONNEES", "o", "​ tracer et exploiter un nuage de points"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap A : Analyse de l’Information chiffrée › III.​ TRAITEMENT DES DONNEES AVEC UN TABLEUR", "o", "​ connaître les fonctionnalités de base des tableurs (moyenne, somme,...) et savoir les coder."],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "A l’aide d’un tableau d’effectif croisés:"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "​ calculer une fréquence"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "​ calculer une fréquence marginale"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "​ calculer une fréquence conditionnelle"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "Construire un arbre pondéré"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "Calculer une probabilité conditionnelle"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "Calculer la probabilité de l’intersection ou de la réunion de deux évènements"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap B : Probabilités conditionnelles", "o", "Déterminer l’indépendance de deux évènements."],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C1 : Fonctions affines › I.​ Reconnaître une fonction affine", "o", "​ connaître la forme générale d’une fonction affine, d’une fonction linéaire ou d’une fonction constante connaître la formule du calcul du coefficient directeur (𝑎 = savoir déterminer l’ordonnée à l’origine savoir qu’une fonction affine est représentée par une droite savoir que l’équation réduite d’une telle droite est de la forme y = ax+b savoir lire un coefficient directeur sur un graphique savoir lire une ordonnée à l’origine"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C2 : Généralités sur les suites › I.​ Notion de suites", "o", "​ maîtriser la notion de suite et le vocabulaire associé"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C2 : Généralités sur les suites › I.​ Notion de suites", "o", "​ savoir représenter graphiquement une suite"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C2 : Généralités sur les suites › II.​ Différentes façons de définir une suite", "o", "​ connaître les différentes façons de définir une suite : explicite, par récurrence, avec un programme"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C2 : Généralités sur les suites › III.​ Variations des suites", "o", "​ connaître la notion de variation des suites"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C2 : Généralités sur les suites › III.​ Variations des suites", "o", "​ savoir étudier le sens de variation d’une suite"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › I.​ Définition par récurrence", "o", "​ connaître la formule par récurrence d’une suite arithmétique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › I.​ Définition par récurrence", "o", "​ savoir montrer qu’une suite est arithmétique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › II.​ Formule explicite", "o", "​ Savoir donner la forme explicite d’une suite arithmétique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › II.​ Formule explicite", "o", "​ Savoir que “donner une expression de Un en fonction de n” signifie donner la forme explicite de Un"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › III.​ Représentation graphique et variations", "o", "​ savoir représenter une suite arithmétique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › III.​ Représentation graphique et variations", "o", "​ reconnaître qu’une suite est arithmétique à la forme de son nuage de points"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C3 : Suites arithmétiques › III.​ Représentation graphique et variations", "o", "​ étudier les variations d’une suite arithmétique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › I.​ Définition par récurrence", "o", "​ connaître la formule par récurrence d’une suite géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › I.​ Définition par récurrence", "o", "​ savoir montrer qu’une suite est géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › II.​ Formule explicite", "o", "​ Savoir donner la forme explicite d’une suite géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › II.​ Formule explicite", "o", "​ Savoir que “donner une expression de Un en fonction de n” signifie donner la forme explicite de Un"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › III.​ Représentation graphique et variations", "o", "​ savoir représenter une suite géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C4 : Suites géométriques › III.​ Représentation graphique et variations", "o", "​ étudier les variations d’une suite géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C5 : Fonction exponentielle › I.​ Reconnaître une fonction exponentielle", "o", "​ connaître la forme des fonctions exponentielles de base"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C5 : Fonction exponentielle › I.​ Reconnaître une fonction exponentielle", "o", "​ savoir qu’une fonction exponentielle est le prolongement continu d’une suite géométrique"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C5 : Fonction exponentielle › II.​ Etude des fonction exponentielles", "o", "​ savoir étudier le sens de variation d’une fonction exponentielle"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C5 : Fonction exponentielle › II.​ Etude des fonction exponentielles", "o", "​ savoir représenter graphiquement une fonction exponentielle"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap C5 : Fonction exponentielle › III.​ Propriété des fonctions exponentielles", "o", "​ maîtriser les propriétés algébriques des fonctions exponentielles savoir résoudre une équation avec des racines n-ièmes"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap D1 : Variations instantanées › I.​ Tangente à une courbe en un point", "o", "​ connaître la notion de droite sécante"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap D1 : Variations instantanées › I.​ Tangente à une courbe en un point", "o", "​ connaître la notion de droite tangente à une courbe"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap D1 : Variations instantanées › II.​ Nombre dérivé", "o", "​ savoir lire un nombre dérivé (éventuellement,commencer par tracer la tangente à la courbe si elle n’y est pas)"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap D1 : Variations instantanées › II.​ Nombre dérivé", "o", "​ faire le lien entre nombre dérivé, coefficient directeur de tangente et vitesse instantanée"],
["1re (ens. scientifique)", "Mon bilan par chapitre", "Chap D1 : Variations instantanées › II.​ Nombre dérivé", "o", "​ déterminer l’équation réduite d’une tangente."]
);
